### ISSUE TITLE
undefined reference to `putchar_int32'

### ISSUE THREAD

**Issue by mahdix** [igor84/summus#2]
When I try to compile and run one of test files, I see above error.

1. Build the project so you have `summus` in `bin` dir.
2. `./summus ../tests/test.smm -o test.ll` runs without an issue.
3. `clang -x ir -o test test.ll`

This gives you `undefined reference` error. 

OS: Ubuntu 
Installed: Clang, LLVM, LibZ

**Comment by mahdix** [comment]
I tried to edit generated `ll` file manually and change `putchar_32` to `putchar` and it seems to be working fine (Both using clang or by running `lli` to execute ll file).

**Comment by igor84** [comment]
Thanks for reporting this. I think I fixed it. You can see the change I made in compiler/smmtypeinference.c file.

**Comment by mahdix** [comment]
Thanks. I can confirm the problem is fixed.
